### ISSUE TITLE
Bug: Network routing isn't working properly out of the box

### ISSUE THREAD

**Issue by jdarling** [nearform/otlp-blueprint#186]
Currently when you just clone and run `docker compose --verbose up --build` the application and server can't reach the Jaeger backend as otlp-blueprint.local isn't known or setup properly

Fix, set hostname in the docker-compose.yml file for each of the services.

EG (jaeger):

```
  jaeger:
    image: jaegertracing/all-in-one:1.38.1
    hostname: jaeger-service.otlp-blueprint.local
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16685:16685"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - jaeger-network
```
